### ISSUE TITLE
pbreplicate repeat and if statment

### ISSUE THREAD

**Issue by Bioscar** [psolymos/pbapply#16]
To whom it may concern,

I think that your package is great and quite useful for make simulations, but when I try a function like this:

repeat{
if(   ) {break}
}

I found that the calculated time is not precise  and I would like to communicate this incident to you, so maybe you can fix it.

Thanks for reading

Óscar

**Comment by psolymos** [comment]
@Bioscar : thanks for reporting the issue. My guess is that `break` makes the processing time of each unit evaluation variable and only approximate. Similarly to this (you need to run it to see remaining time going back and forth):

```{r}
system.time(pbreplicate(100, Sys.sleep(0.1)))
##   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 10s
##   user  system elapsed 
##  0.122   0.057  10.144 
system.time(pbreplicate(100, Sys.sleep(runif(1, 0, 0.2))))
##   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 10s
##   user  system elapsed 
##  0.119   0.053   9.506 
```

Remaining time is based on extrapolating average from previous steps.
