### ISSUE TITLE
Error when only one core in cluster

### ISSUE THREAD

**Issue by LHMarshall** [psolymos/pbapply#17]
Thanks for this great package!

I found the error message below when running in a Windows XP VM with two cores but my code only allows the user to access one less than the available number so in this case 1 (a rather bizarre thing to do... I hadn't realised this would mean that it would only have one core so not much point in trying to run in parallel but I discovered this small bug so thought I'd report).
```
Error in if (!inherits(cl, "cluster") && cl < 2) cl <- NULL : 
  missing value where TRUE/FALSE needed
```
I traced the error back to the following code in [pblapply](https://github.com/psolymos/pbapply/blob/master/R/pblapply.R) (also pasted in below). When I ran the first check causes cl to become NULL and then throws the error when running the second check.

```
## catch single node requests and forking on Windows
    if (!is.null(cl)) {
        if (inherits(cl, "cluster") && length(cl) < 2L)
            cl <- NULL
        if (!inherits(cl, "cluster") && cl < 2)
            cl <- NULL
        if (!inherits(cl, "cluster") && .Platform$OS.type == "windows")
            cl <- NULL
}
```
```
cl <- NULL
if (!inherits(cl, "cluster") && cl < 2) cat("boo")

Error in if (!inherits(NULL, "cluster") && NULL < 2) cat("boo") : 
  missing value where TRUE/FALSE needed
```

**Comment by psolymos** [comment]
@LHMarshall : thanks for tracing down the issue. Here is how I fixed it:

```
    ## catch single node requests and forking on Windows
    if (!is.null(cl)) {
        if (.Platform$OS.type == "windows") {
            if (!inherits(cl, "cluster"))
                cl <- NULL
        } else {
            if (inherits(cl, "cluster")) {
                if (length(cl) < 2L)
                    cl <- NULL
            } else {
                if (cl < 2)
                    cl <- NULL
            }
        }
    }
```

Now it works as expected and the following code added to unit tests:

```
f <- function(i) Sys.sleep(0.1)
library(parallel)
cl <- makeCluster(1L)
pblapply(1:10, f, cl = cl)
stopCluster(cl)
```
