### ISSUE TITLE
Display a warning if pboptions is not set

### ISSUE THREAD

**Issue by xelibrion** [psolymos/pbapply#18]
I think it would make sense output a warning message if someone used `pb*apply` method, but did not specify call `pboptions` prior to call to `pb*apply`.

**Comment by psolymos** [comment]
@xelibrion : the default options are already set when you load the package. Can you give an example when a warning is needed?

**Comment by xelibrion** [comment]
The behaviour I've seen that if I don't call 
```
pbo <- pboptions(type = "timer")
```
before `pb*apply`, it wasn't really showing any progress. Or maybe it was, but there's no immediate feedback, so it confused me.

**Comment by psolymos** [comment]
It must be related to the `min_time` option. The 1st runs are used to estimate total run time to see if `total_time` > `min_time`. If not, no progress bar is shown. Maybe I should change the code so that it starts showing the bar when `min_time` is 0.

**Comment by psolymos** [comment]
See commit 355ae72d2dcaccce968d5c2565624ad6ce7ed9c5 which closes this.
