### ISSUE TITLE
Determine precedence for nested pb

### ISSUE THREAD

**Issue by psolymos** [psolymos/pbapply#22]
The 1st pb should take precedence over subsequent nested pb calls.

```
f <- function(x) Sys.sleep(0.1)
ff <- function(x) pblapply(1:10, f)
tmp <- lapply(1:10, ff)
tmp <- pblapply(1:10, ff)
```

Outputs are identical (10x pb), but we want only one pb.

Setting type to none is not a solution here because it will simply not show anything.

Switching inside a function between `lapply` and `pblapply` depending on a T/F switch is clumsy.

Need to set a boolean option on load, e.g. `pb.in.progress` and evaluate that in `dopb`. `dopb` also needs to be consolidated (win/unix version in single file).

**Comment by psolymos** [comment]
It looks like that `pboptions` can be used in multiple ways, the 1st is a hack, the second is the preferred way:

```
f <- function(x) Sys.sleep(0.1)
ff <- function(x) {
    options("knitr.in.progress" = TRUE)
    on.exit(options("knitr.in.progress" = NULL))
    pblapply(1:10, f)
}
tmp <- pblapply(1:10, ff)

ff <- function(x) {
    opb <- pboptions(type="none")
    on.exit(pboptions(opb))
    pblapply(1:10, f)
}
tmp <- pblapply(1:10, ff)
```

Example added to help page `?pboptions`.

**Comment by kendonB** [comment]
A wonderful outcome here would be for the nested pb's to be combined somehow. Say the outside progress bar has 5 elements to go through, and the inside ones each have 20, a tick on the inside one could move the outside one by 1/100th. Is this possible?

The main application for me would be when parallelizing. I often split a parallel operation into the number of threads (or some multiple thereof), then each one has a large job to do. In this case, the outside pb doesn't provide much information.

**Comment by psolymos** [comment]
@kendonB: let me know of the above example works as expected. It works fine for my use case. I have a function which makes a pb. When I do LOO cross validation, I want the LOO loop to show the pb, and switch off pb for the inside function.

It turned out simpler to solve than expected.

**Comment by kendonB** [comment]
For me, the above does work and I only see one pb. However, my suggestion was that, instead of the pb stepping through 10% at a time, it would step through 1% at a time based on the combined progress of the inside and outside pb's.

**Comment by kendonB** [comment]
I'm imagining a case where the outside pb is very slow, and the user benefits from seeing the progress of the inside one.

**Comment by psolymos** [comment]
Sounds a bit more complicated. Will open a separate issue for it.
