### ISSUE TITLE
pbapply parallel

### ISSUE THREAD

**Issue by pbulsink** [psolymos/pbapply#24]
I know a number of the functions were parallelized in PR #10 as requested in issue #9, but that fails to parallelize `pbapply(X, MARGIN, FUN, ...) `. If there's not a particular block, could that be added?

**Comment by psolymos** [comment]
It would require a rewrite, but it is doable.

The reason it is not implemented is that it has a loop with `setpb`/`closepb` etc in it following the original `apply` code as close as possible.

Adding parallel support would be achieved by using `pblapply`. Here is how I think it can be done:

1. add `cl` argument with `NULL` as default -- this would mean no change.
2. call `pblapply` when `!is.null(cl)` and post process the output.
3. add test suite that checks if return objects are identical.

**Comment by pbulsink** [comment]
To use pblapply over rows, would you need to transpose the original data frame first? 
`df<-data.frame(x=runif(5), y=runif(5), z=runif(5)
lapply(df, sum) #column sums
lapply(as.data.frame(t(df)), sums) #row sums
`
This could run into some memory problems if the data frame is large. Any other suggestions for wrapping apply as lapply?

**Comment by kendonB** [comment]
``lapply(seq_len(nrow(df), yourfunction)``? The smartest thing to do depends on the actual operation you're doing. *apply loops are slow.

**Comment by psolymos** [comment]
I was thinking something like:

```
if (is.null(cl)) {
  bpapply(X, MARGIN, FUN, ...) # this is to be wrapped inside
} else {
  if (MARGIN==1) {
    pblapply(seq_len(NROW(X)), function(i, ...) FUN(X[i,], ...))
  } else {
    pblapply(seq_len(NCOL(X)), function(i, ...) FUN(X[,i], ...))
  }
}
```

This would not require transpose.

**Comment by psolymos** [comment]
I could forge together a solution based on `parallel::parApply` which turned out to follow the same logic as `base::apply` and happened to use `parLapply` which was then substituted by `parlapply`. Easy peasy. See pbapply-parallel branch. Just waiting for test to pass and will merge it with master.

**Comment by psolymos** [comment]
PR #25 closed this issue.
