### ISSUE TITLE
 load balancing

### ISSUE THREAD

**Issue by TarasDerevianko** [psolymos/pbapply#28]
The parLapplyLB is better choice for parallelization task. 

Could you change this in the next version of package?

**Comment by psolymos** [comment]
I can add an option to switch to LB. I would not prefer LB as the default, as the sequence of job execution is not reproducible with LB.

**Comment by psolymos** [comment]
This will switch on load balancing for parallel clusters:

```
library(pbapply)
pboptions(use_lb=TRUE)
```
