### ISSUE TITLE
pbapply runs the parallel batches sequentially and not in parallel

### ISSUE THREAD

**Issue by psolymos** [psolymos/pbapply#34]
It seems (at least on Linux and MacOS... got no Windows) that pbapply runs the parallel batches sequentially and not in parallel.

MRE:

```R
test <- function(i) {
  system.time(Sys.sleep(i))[["elapsed"]]
  }

system.time(foo <- pbapply::pblapply(c(1, 15, 1, 15), test, cl = 2L))
unlist(foo)
```

This should last ~ 17 not 30 seconds in an ideal world.
pbapply waits that the first 15 job is finished before moving on.

For comparison, foreach does the job as expected (but require horrible coding):

```R
pb <- utils::txtProgressBar(max = 4, style = 3)
progress <- function(n) utils::setTxtProgressBar(pb, n)
opts <- list(progress = progress)
cl <- parallel::makeCluster(2)
doSNOW::registerDoSNOW(cl)
boot <- foreach::foreach(i = c(1, 15, 1, 15), .options.snow = opts)
system.time(foo <- foreach::`%dopar%`(boot, test(i)))
parallel::stopCluster(cl)
unlist(foo)
```

It may be a design choice but maybe not.

I hope this help!

**Comment by psolymos** [comment]
Batches are made so that pb can be updated in between. This does not quite allow load balancing to reach full efficiency. So what pbapply does is geared more towards equally sized jobs. Estimating runtime is also difficult with variable run times, but of course % of jobs complete still make sense.

Sending all the jobs with load balancing gives the desired outcome, but without a progress bar:

```R
cl <- makePSOCKcluster(2L)
system.time(foo <- parallel::parLapplyLB(cl, c(1, 15, 1, 15), test))
unlist(foo)
stopCluster(cl)
```
With equal run times, both are the same:

```R
library(foreach)
library(doSNOW)
pb <- utils::txtProgressBar(max = 4, style = 3)
progress <- function(n) utils::setTxtProgressBar(pb, n)
opts <- list(progress = progress)
cl <- parallel::makeCluster(2)
doSNOW::registerDoSNOW(cl)
boot <- foreach::foreach(i = c(5, 5, 5, 5), .options.snow = opts)
system.time(foo <- foreach::`%dopar%`(boot, test(i)))
parallel::stopCluster(cl)
unlist(foo)

library(pbapply)
library(parallel)
test <- function(i) {
  system.time(Sys.sleep(i))[["elapsed"]]
}
system.time(foo <- pbapply::pblapply(c(5, 5, 5, 5), test, cl = 2L))
unlist(foo)
```

If run times are know approximately, there much more efficient schedules, e.g. as implemented in `dclone::clusterSplitSB` (I call it 'size balancing', see [here](https://github.com/datacloning/dclone/blob/master/R/clusterSplitSB.R)).

**Comment by courtiol** [comment]
Many thanks  @psolymos for the explanation!

I am using pbapply to refit models after bootstrapping the data.
Therefore the timing cannot be anticipated.

In this context, I am a bit confused by the package option ```use_lb```.
The documentation specifies for ```use_lb```: 

> Switch for using load balancing when running in parallel clusters.

Setting the value to ```TRUE``` with my MRE (see above) did not help.
Which are the conditions under which the option is actually effective?

Many thanks!

**Comment by psolymos** [comment]
I agree, `use_lb` as currently implemented is not that helpful when number of cores/workers is small.
