### ISSUE TITLE
progress bar doesn't erase previously printed characters if new output length < old output length

### ISSUE THREAD

**Issue by kotoroshinoto** [psolymos/pbapply#37]
progress bar doesn't erase previously printed characters if new output length < old output length

this in my experience, has happened when the remaining/elapsed timer text changes and near or at the end of the processing, there are several fewer characters than there were in the middle of the processing.

Perhaps you should track maximum length, or last printed length and use that to erase the extra characters by printing extra whitespace characters at the end or something.

**Comment by kotoroshinoto** [comment]
![image](https://user-images.githubusercontent.com/1337560/58384171-b20fe780-7fac-11e9-81c9-41df118e09a2.png)
it looks like this, see beyond the ~00s there is a 0ss left over from previous prints.
![image](https://user-images.githubusercontent.com/1337560/58384179-cf44b600-7fac-11e9-8bb0-cf4abaa98ef6.png)
in this case its showing an extra 14s beyond the last print.

**Comment by psolymos** [comment]
Interesting. Thanks for reporting, I'll look into it.
