### ISSUE TITLE
Error in environment(pbmapply): object 'pbmapply' not found

### ISSUE THREAD

**Issue by Nowosad** [psolymos/pbapply#39]
I am working on a package using **pbapply** and the `pbmapply()` function. 
This function works well in an interactive session after attaching **pbapply**, however there is an error while just calling the function using `::`.

``` r
pbapply::pbmapply(rep, 1:4, 4:1)
#> Error in environment(pbmapply): object 'pbmapply' not found

library(pbapply)
pbmapply(rep, 1:4, 4:1)
#> [[1]]
#> [1] 1 1 1 1
#> 
#> [[2]]
#> [1] 2 2 2
#> 
#> [[3]]
#> [1] 3 3
#> 
#> [[4]]
#> [1] 4
```

<sup>Created on 2019-08-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by psolymos** [comment]
{pbapply} exports the `pbmapply` function. How does your `DESCRIPTION` look like? Is {pbapply} listed in Depends or Imports field? You need to list it as Imports to be able to access via `::` without explicitly importing in `NAMESPACE`.

**Comment by Nowosad** [comment]
Hi @psolymos ,
I have it in Suggests following the advice at https://github.com/psolymos/pbapply#1-suggests-pbapply.
BTW `pbapply::pbreplicate()` and `pbapply::pblapply()` work without any problems...

**Comment by psolymos** [comment]
I see. The issue is with `environment(pbmapply)` used inside the tracer. Try installing this branch and see if it helps: https://github.com/psolymos/pbapply/tree/issue-%2339-pbmapply-env

@zzawadz can you have a look too? 
https://github.com/psolymos/pbapply/commits/issue-%2339-pbmapply-env

**Comment by Nowosad** [comment]
The error message has changed to `Error in eval(expr, p) : object '.pb_env' not found`.
You can try it using my PR - https://github.com/psolymos/pbapplySuggests/pull/1.

**Comment by psolymos** [comment]
{pbapplySuggests} fails on Travis because it pulls {pbapply} from CRAN. It works locally after this commit https://github.com/psolymos/pbapply/commit/f98a70a105b9008db94b9c6fd04ad25ce44d4159

**Comment by Nowosad** [comment]
@psolymos it works now. Thank you!

**Comment by Nowosad** [comment]
Dear @psolymos, would it be possible to upload this package version to CRAN?

**Comment by psolymos** [comment]
Yes, I'll prepare an update in the next few days.

**Comment by psolymos** [comment]
@Nowosad pbapply_1.4-2.tar.gz is on its way to CRAN.
