### ISSUE TITLE
Progress bar inside the function

### ISSUE THREAD

**Issue by adayim** [psolymos/pbapply#43]
Hi, I have a loop inside a function and I am also calling this function with `lapply`. I tried to call the progress bar inside the loop it does not work. Although I can achieve this using by passing the the `bp` to the function.
```r
fun1 <- function() {
  pb <- startpb(0, 100)
  on.exit(closepb(pb))
  am_loop(100) # this would a pblapply or lapply.
  invisible(NULL)
}

am_loop <- function(x){
  for(i in 1:x){
    Sys.sleep(0.05)
    setpb(pb, getpb(pb) + 1) # Want it add one without knowing the index, useful when looping the value not index.
  }
}

fun1()
```

Also, is it possible to have a format for the progress bar so can add some leading and tailing text, like `progress` package?

**Comment by psolymos** [comment]
Yes, it works when you pass the `pb` to the `am_loop` function:

```R
fun1 <- function() {
  pb <- startpb(0, 100)
  on.exit(closepb(pb))
  am_loop(100, pb)
  invisible(NULL)
}

am_loop <- function(x, pb){
  for(i in 1:x){
    Sys.sleep(0.05)
    setpb(pb, getpb(pb) + 1)
  }
}

fun1()
```

The problem with using `lapply` and `pbapply` is that you only have a single value, 100, so the bar would jump from 0 to 100% upon completion.

There is no way of adding custom leading/tailing text.

**Comment by adayim** [comment]
That's good to know, thanks.
