### ISSUE TITLE
Function for pb.mapply

### ISSUE THREAD

**Issue by GreatEmerald** [psolymos/pbapply#46]
It's nice that `mapply` has a pb variant! But what about `.mapply()`? It's the "barebones" version without additional arguments, but also it has a handy `dots` argument instead of `...`, which allows to skip a call to `do.call()` to parse the dots. It seems pretty straight-forward to implement this function based on the `pbmapply` code?

**Comment by psolymos** [comment]
Hey @GreatEmerald check the new dev version from gh if this is what you had in mind. See examples `?pb.mapply`.
