### ISSUE TITLE
License compatibility GPL-2

### ISSUE THREAD

**Issue by mrtnb** [psolymos/pbapply#61]
The pbapply package is licensed under GPL-2. Are there any issues with depending on this package within code licensed under GPL-3? If so, are there any plans to upgrade pbapply e.g. GPL-3 or GPL-2+?

**Comment by psolymos** [comment]
@mrtnb thanks for bringing this up. It is timely to revisit the initial GPL-2 license now that the package has new contributors. The devel version borrows from future.apply, which borrows from base R.

Relicensing similarly to the future packages and R itself would make sense: 

[GPL-2](https://cran.r-project.org/web/licenses/GPL-2) | [GPL-3](https://cran.r-project.org/web/licenses/GPL-3) [expanded from: GPL (≥ 2)]

@zzawadz and @HenrikBengtsson please give consent to the license change in the comments below if you are in favor.

**Comment by HenrikBengtsson** [comment]
Fine with me

**Comment by zzawadz** [comment]
I am ok with that.
