### ISSUE TITLE
Option `nout` does not seem to work with `pbapply`

### ISSUE THREAD

**Issue by GFabien** [psolymos/pbapply#62]
Hi, thank you for the package. It is very convenient! 
In my code, I have to call `apply` on a large matrix, which takes time, so I added a progress bar, so the user did not feel like the code was stuck. Therefore, I replaced `apply` with `pbapply::pbapply`. It works like a charm but significantly increases computation time (almost doubles). I wondered if the number of progress bar updates was responsible for the overload and tried to fix it by lowering `nout` from the `pboptions`. While it seems to have the expected effect with other functions like `pblapply` or `pbtapply`, it does not seem to work for `pbapply`. Here is a small snippet to demonstrate this issue:
``` R
pbapply::pboptions(type = "timer", nout = 4L)
x <- matrix(rnorm(10000 * 5), 10000, 5)
y <- pbapply::pbapply(x, 1, mean)
z <- pbapply::pblapply(rep(x, 5), mean)
```
I am using `pbapply` version `1.6-0`. Thank you for your help!

**Comment by psolymos** [comment]
@GFabien thanks for the report. I can see that `pbapply` takes much longer. But the `pblapply` line of yours does not really do the same thing. I would try this, as `pbsapply` seem to be much faster (same as `sapply`):

```R
library(pbapply)

pbapply::pboptions(type = "timer", nout = 4L)

x <- matrix(rnorm(10000 * 5), 10000, 5)
y <- pbapply::pbapply(x, 1, mean)
z <- pbapply::pbsapply(seq_len(nrow(x)), function(i) mean(x[i,]))
all(y == z)


system.time(pbapply::pbapply(x, 1, mean))
system.time(pbapply::pbsapply(seq_len(nrow(x)), function(i) mean(x[i,])))
system.time(apply(x, 1, mean))
system.time(sapply(seq_len(nrow(x)), function(i) mean(x[i,])))
```

**Comment by GFabien** [comment]
I'm sorry I wasn't clear. The snippet was not supposed to produce the same results with the two functions but illustrate the different progress bar behavior.

**Comment by psolymos** [comment]
No problem. The gh version of the package is now almost as fast as the base equivalent.
