### ISSUE TITLE
pblapply errors as Suggest in github action

### ISSUE THREAD

**Issue by stemangiola** [psolymos/pbapply#65]
For some reason I get 

Error: Package suggested but not available: ‘pblapply’ (this happens to linux, windows, and Mac)

https://github.com/stemangiola/tidybulk/actions/runs/5499982860/jobs/10022583430?pr=275#step:20:48

**Comment by psolymos** [comment]
There is no such package as pblapply. From what I can tell, your package lists Seurat & DESeq2 in the Suggests field which both suggest or import from pbapply. But there could be others that your dependencies list as their dependencies. It is hard to tell what is causing this. I would add another gh action that would install the dependencies explicitly one by one. That way you can see which package is causing the issue and reach out to the maintainer.

**Comment by stemangiola** [comment]
Thanks my bad for the typo :)
