### ISSUE TITLE
Issue in the progress bar in Shiny

### ISSUE THREAD

**Issue by svalvaro** [psolymos/pbapply#69]
In the same example that you have in the Readme, change the sleep time to 5s, to see the bug better.
```
library(shiny)
library(pbapply)

pboptions(
    type = "shiny",
    title = "Shiny progress",
    label = "Almost there ...")

ui <- fluidPage(
    plotOutput("plot")
)

server <- function(input, output, session) {
    output$plot <- renderPlot({
        pbsapply(1:15, function(z) Sys.sleep(5))
        plot(cars)
    })
}
shinyApp(ui, server)
```
![Screenshot 2024-07-16 at 12 58 15](https://github.com/user-attachments/assets/35db0c3e-0ad9-4bd9-8a06-3ffe801a2503)
This "Message" stays there until the first thread has finished computing, then it shows the correct progress bar.

**Comment by psolymos** [comment]
@svalvaro thanks for reporting the issue. The message is now set immediately after creating the pb object.
